import { createContext, useContext } from 'react';
import type { ReactNode } from 'react';
import { useText } from '../ui';
export const InheritanceContext = createContext<string[]>([]);

export function Toggle({ label, checked, change, help, disabled = false }: Readonly<{ label: string; checked: boolean; change: (value: boolean) => void; help?: string; disabled?: boolean }>) { return <div className="config-toggle"><label className="checkbox-label"><input type="checkbox" checked={checked} disabled={disabled} onChange={e => change(e.target.checked)} /><span>{label}</span></label>{help && <p className="field-help">{help}</p>}</div>; }
export function Lines({ label, values, change, help, disabled = false }: Readonly<{ label: string; values: string[]; change: (values: string[]) => void; help?: string; disabled?: boolean }>) { return <label>{label}<textarea rows={4} disabled={disabled} value={values.join('\n')} onChange={e => change(e.target.value.split('\n'))} />{help && <span className="field-help">{help}</span>}</label>; }
export function Mode({ label, value, change, off = false, redirect = false }: Readonly<{ label: string; value: string; change: (value: string) => void; off?: boolean; redirect?: boolean }>) { const t = useText(); return <label>{label}<select value={value} onChange={e => change(e.target.value)}>{off && <option value="off">{t("off")}</option>}<option value="observe">{t("observe")}</option><option value="block">{t("block")}</option>{redirect && <option value="redirect">{t("redirect")}</option>}</select></label>; }
export function ConfigBlock({ title, description, children, section }: Readonly<{ title: string; description?: string; children: ReactNode; section?: string }>) { const inherited = useContext(InheritanceContext); return <section className="config-block"><div><h3>{title}</h3>{description && <p>{description}</p>}</div><fieldset className="config-block-fields" disabled={Boolean(section && inherited.includes(section))}>{children}</fieldset></section>; }
export function Categories({ values, change, allowed, disabled = false, hints }: Readonly<{ values: string[]; change: (values: string[]) => void; allowed: string[]; disabled?: boolean; hints?: Record<string, string> }>) { const t = useText(); const labels: Record<string, string> = { email: t("email"), phone: t("phone"), iban: 'IBAN', card: t("paymentCard"), social_id: t("socialIdentifierFrance"), ssn_us: t("socialSecurityNumberUnitedStates"), ip: t("ipAddress"), source_code: t("sourceCode"), medical: t("medicalData"), keyword: t("keywords") }; return <div className="category-grid">{allowed.map(type => <Toggle key={type} label={labels[type] ?? type} help={hints?.[type]} disabled={disabled} checked={values.includes(type)} change={on => change(on ? [...values, type] : values.filter(item => item !== type))} />)}</div>; }
export function CapabilityNote({ available, children }: Readonly<{ available: boolean; children: ReactNode }>) { return available ? null : <p className="capability-note">{children}</p>; }
