import type { TranslationKey } from '../locales/en';

/** Generated from provider.md -- do not hand-edit; regenerate when the inventory moves.
 *
 * The grouping lives here rather than in the signed catalogue on purpose: a category is
 * an editorial convenience for one console screen, and adding a field to
 * `known_platforms` would impose the "field first, catalogue second" delivery order --
 * a tolerant extension, agent and server shipped to the fleet before the catalogue may
 * carry it. Nothing about presence detection depends on these labels.
 */
export const PLATFORM_CATEGORIES = [
  'aggregators',
  'generalAssistants',
  'codingAssistants',
  'imageVideoAudio',
  'writingProductivity',
  'meetingsTranscription',
  'researchScience',
  'agentsAutomation',
  'apiConsoles',
  'localApplications',
  'industryVerticals',
  'sharedHostPathScoped',
] as const;
export type PlatformCategory = (typeof PLATFORM_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<PlatformCategory, TranslationKey> = {
  aggregators: 'platformCategoryAggregators',
  generalAssistants: 'platformCategoryGeneralAssistants',
  codingAssistants: 'platformCategoryCodingAssistants',
  imageVideoAudio: 'platformCategoryImageVideoAudio',
  writingProductivity: 'platformCategoryWritingProductivity',
  meetingsTranscription: 'platformCategoryMeetingsTranscription',
  researchScience: 'platformCategoryResearchScience',
  agentsAutomation: 'platformCategoryAgentsAutomation',
  apiConsoles: 'platformCategoryApiConsoles',
  localApplications: 'platformCategoryLocalApplications',
  industryVerticals: 'platformCategoryIndustryVerticals',
  sharedHostPathScoped: 'platformCategorySharedHostPathScoped',
};

/** A platform the catalogue names but this table does not is grouped under "Other"
 *  rather than dropped: a published catalogue may carry entries this build predates. */
export const PLATFORM_CATEGORY: Record<string, PlatformCategory> = {
  // 18
  mammouth: 'aggregators',
  poe: 'aggregators',
  openrouter: 'aggregators',
  typingmind: 'aggregators',
  chathub: 'aggregators',
  sider: 'aggregators',
  merlin: 'aggregators',
  harpa: 'aggregators',
  maxai: 'aggregators',
  monica: 'aggregators',
  straico: 'aggregators',
  t3chat: 'aggregators',
  lmarena: 'aggregators',
  flowgpt: 'aggregators',
  glhf: 'aggregators',
  abacus: 'aggregators',
  youcom: 'aggregators',
  wiseone: 'aggregators',
  // 23
  gemini: 'generalAssistants',
  copilot: 'generalAssistants',
  lechat: 'generalAssistants',
  deepseek: 'generalAssistants',
  perplexity: 'generalAssistants',
  grok: 'generalAssistants',
  notebooklm: 'generalAssistants',
  aistudio: 'generalAssistants',
  metaai: 'generalAssistants',
  pi: 'generalAssistants',
  character: 'generalAssistants',
  qwen: 'generalAssistants',
  kimi: 'generalAssistants',
  doubao: 'generalAssistants',
  yuanbao: 'generalAssistants',
  chatglm: 'generalAssistants',
  ernie: 'generalAssistants',
  minimax: 'generalAssistants',
  tiangong: 'generalAssistants',
  coze: 'generalAssistants',
  duckai: 'generalAssistants',
  komo: 'generalAssistants',
  andi: 'generalAssistants',
  // 17
  cursor: 'codingAssistants',
  windsurf: 'codingAssistants',
  tabnine: 'codingAssistants',
  replit: 'codingAssistants',
  v0: 'codingAssistants',
  bolt: 'codingAssistants',
  lovable: 'codingAssistants',
  sourcegraph: 'codingAssistants',
  qodo: 'codingAssistants',
  blackbox: 'codingAssistants',
  phind: 'codingAssistants',
  devin: 'codingAssistants',
  continue: 'codingAssistants',
  magic: 'codingAssistants',
  augment: 'codingAssistants',
  zed: 'codingAssistants',
  warp: 'codingAssistants',
  // 25
  midjourney: 'imageVideoAudio',
  sora: 'imageVideoAudio',
  dalle: 'imageVideoAudio',
  firefly: 'imageVideoAudio',
  leonardo: 'imageVideoAudio',
  ideogram: 'imageVideoAudio',
  civitai: 'imageVideoAudio',
  clipdrop: 'imageVideoAudio',
  stability: 'imageVideoAudio',
  runway: 'imageVideoAudio',
  pika: 'imageVideoAudio',
  luma: 'imageVideoAudio',
  kling: 'imageVideoAudio',
  heygen: 'imageVideoAudio',
  synthesia: 'imageVideoAudio',
  did: 'imageVideoAudio',
  elevenlabs: 'imageVideoAudio',
  suno: 'imageVideoAudio',
  udio: 'imageVideoAudio',
  descript: 'imageVideoAudio',
  krea: 'imageVideoAudio',
  playground: 'imageVideoAudio',
  recraft: 'imageVideoAudio',
  flux: 'imageVideoAudio',
  photoroom: 'imageVideoAudio',
  // 12
  jasper: 'writingProductivity',
  copyai: 'writingProductivity',
  writesonic: 'writingProductivity',
  rytr: 'writingProductivity',
  quillbot: 'writingProductivity',
  wordtune: 'writingProductivity',
  sudowrite: 'writingProductivity',
  gamma: 'writingProductivity',
  tome: 'writingProductivity',
  beautifulai: 'writingProductivity',
  writer: 'writingProductivity',
  napkin: 'writingProductivity',
  // 10
  otter: 'meetingsTranscription',
  fireflies: 'meetingsTranscription',
  fathom: 'meetingsTranscription',
  tldv: 'meetingsTranscription',
  readai: 'meetingsTranscription',
  avoma: 'meetingsTranscription',
  supernormal: 'meetingsTranscription',
  granola: 'meetingsTranscription',
  circleback: 'meetingsTranscription',
  notta: 'meetingsTranscription',
  // 7
  consensus: 'researchScience',
  elicit: 'researchScience',
  scite: 'researchScience',
  scholarcy: 'researchScience',
  exa: 'researchScience',
  felo: 'researchScience',
  genspark: 'researchScience',
  // 8
  manus: 'agentsAutomation',
  dify: 'agentsAutomation',
  relevanceai: 'agentsAutomation',
  lindy: 'agentsAutomation',
  flowise: 'agentsAutomation',
  langflow: 'agentsAutomation',
  dust: 'agentsAutomation',
  browseruse: 'agentsAutomation',
  // 20
  'openai-platform': 'apiConsoles',
  'anthropic-console': 'apiConsoles',
  'google-ai-dev': 'apiConsoles',
  'xai-console': 'apiConsoles',
  groq: 'apiConsoles',
  replicate: 'apiConsoles',
  together: 'apiConsoles',
  fireworks: 'apiConsoles',
  deepinfra: 'apiConsoles',
  modal: 'apiConsoles',
  cohere: 'apiConsoles',
  ai21: 'apiConsoles',
  reka: 'apiConsoles',
  zeroone: 'apiConsoles',
  alephalpha: 'apiConsoles',
  lighton: 'apiConsoles',
  silo: 'apiConsoles',
  langsmith: 'apiConsoles',
  wandb: 'apiConsoles',
  'azure-openai': 'apiConsoles',
  // 6
  ollama: 'localApplications',
  lmstudio: 'localApplications',
  jan: 'localApplications',
  msty: 'localApplications',
  nomic: 'localApplications',
  anythingllm: 'localApplications',
  // 16
  harvey: 'industryVerticals',
  casetext: 'industryVerticals',
  spellbook: 'industryVerticals',
  luminance: 'industryVerticals',
  robin: 'industryVerticals',
  doctrine: 'industryVerticals',
  jimini: 'industryVerticals',
  abridge: 'industryVerticals',
  glasshealth: 'industryVerticals',
  hippocratic: 'industryVerticals',
  nabla: 'industryVerticals',
  regie: 'industryVerticals',
  lavender: 'industryVerticals',
  clay: 'industryVerticals',
  instantly: 'industryVerticals',
  julius: 'industryVerticals',
  // 10
  'github-copilot': 'sharedHostPathScoped',
  'x-grok': 'sharedHostPathScoped',
  'ddg-ai': 'sharedHostPathScoped',
  'bing-chat': 'sharedHostPathScoped',
  'vertex-ai': 'sharedHostPathScoped',
  'm365-copilot': 'sharedHostPathScoped',
  'copilot-studio': 'sharedHostPathScoped',
  'teams-copilot': 'sharedHostPathScoped',
  'slack-ai': 'sharedHostPathScoped',
  'atlassian-rovo': 'sharedHostPathScoped',
};
