import { randomBytes } from 'node:crypto';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { flows } from './identity-flows.mjs';
const root=new URL('../',import.meta.url),local=new URL('.local/generated/',root),envPath=new URL('.env',root);
await mkdir(local,{recursive:true});try{await access(envPath);console.log('Existing local configuration preserved.');process.exit(0)}catch{}
const secret=()=>randomBytes(32).toString('hex');
const env={DB_ADMIN_PASSWORD:secret(),DB_RUNTIME_PASSWORD:secret(),DB_MIGRATION_PASSWORD:secret(),IDENTITY_DB_PASSWORD:secret(),IDENTITY_ADMIN_PASSWORD:secret(),OIDC_CLIENT_SECRET:secret(),OIDC_ADMIN_CLIENT_SECRET:secret(),SESSION_KEY:randomBytes(32).toString('base64'),CONTENT_KEYS:'1:'+randomBytes(32).toString('base64'),POLICY_SIGNING_KEY:randomBytes(32).toString('base64'),MILVAGO_EDITION:'community',MILVAGO_SETUP_TOKEN:randomBytes(32).toString('base64url')};
const realm={...flows(),realm:'milvago',enabled:true,displayName:'Milvago',loginTheme:'milvago',emailTheme:'milvago',registrationAllowed:false,verifyEmail:true,resetPasswordAllowed:true,rememberMe:false,sslRequired:'external',bruteForceProtected:true,passwordPolicy:'length(12) and maxLength(128) and notUsername and notEmail',internationalizationEnabled:true,supportedLocales:['fr','en','es','pt-BR'],defaultLocale:'en',smtpServer:{host:'mail',port:'1025',from:'no-reply@milvago.test',fromDisplayName:'Milvago',auth:'false',ssl:'false',starttls:'false'},clients:[{clientId:'milvago-console',name:'Milvago',enabled:true,protocol:'openid-connect',publicClient:false,secret:env.OIDC_CLIENT_SECRET,standardFlowEnabled:true,directAccessGrantsEnabled:false,redirectUris:['http://localhost:4020/auth/callback'],webOrigins:['http://localhost:4020'],attributes:{'pkce.code.challenge.method':'S256','post.logout.redirect.uris':'http://localhost:4020/*'},defaultClientScopes:['basic','profile','email','roles','acr']},{clientId:'milvago-management',enabled:true,protocol:'openid-connect',publicClient:false,secret:env.OIDC_ADMIN_CLIENT_SECRET,serviceAccountsEnabled:true,standardFlowEnabled:false,directAccessGrantsEnabled:false}],users:[{username:'service-account-milvago-management',enabled:true,serviceAccountClientId:'milvago-management',clientRoles:{'realm-management':['manage-users','query-users','view-users','manage-realm','view-realm','manage-clients','view-clients','manage-identity-providers','view-identity-providers']}}]};
await writeFile(new URL('realm.json',local),JSON.stringify(realm,null,2),{mode:0o600,flag:'wx'});await writeFile(envPath,Object.entries(env).map(([key,value])=>key+'='+value).join('\n')+'\n',{mode:0o600,flag:'wx'});console.log('Fresh Community configuration generated. Start the stack, open the console and enter MILVAGO_SETUP_TOKEN from .env to create the first administrator.');
